// <auto-generated />
using System;
using FitFusion.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitFusion.Api.Migrations
{
    [DbContext(typeof(FitFusionDbContext))]
    [Migration("20260513160015_AddDishes")]
    partial class AddDishes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("FitFusion.Api.Models.Entities.Dish", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<float>("CarbsPer100g")
                        .HasColumnType("REAL");

                    b.Property<float>("DefaultPortionG")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<float>("FatsPer100g")
                        .HasColumnType("REAL");

                    b.Property<float>("KcalPer100g")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<float>("ProteinPer100g")
                        .HasColumnType("REAL");

                    b.Property<string>("SuitableSlots")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("FitFusion.Api.Models.Entities.UserProfile", b =>
                {
                    b.Property<string>("Uid")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityLevel")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sex")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetCarbsG")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetFatG")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetKcal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetProteinG")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<float?>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Uid");

                    b.HasIndex("Email");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("FitFusion.Api.Models.Entities.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KcalEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUid", "PerformedAt");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("FitFusion.Api.Models.Entities.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Intensity")
                        .HasColumnType("TEXT");

                    b.Property<string>("MuscleGroup")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sets")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("WeightKg")
                        .HasColumnType("REAL");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutExercises");
                });

            modelBuilder.Entity("FitFusion.Api.Models.Entities.WorkoutExercise", b =>
                {
                    b.HasOne("FitFusion.Api.Models.Entities.Workout", "Workout")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("FitFusion.Api.Models.Entities.Workout", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
